### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by palomahnhp** [IAMCorporativos/ancar#213]
Este issues contiene pequeñas correcciones y mejoras que no implican un issue:   

**Genéricos:**
- [ ] Opción Salir => cierre sesión y mensaje rojo y/o cerrar ventana tras un segundo  
- [ ] Cambio escudo a última versión => Calidad ya ha publicado el nuevo logo para Intranet 154X50
- [x] PDF Resumen:  sacar los totales de tfoot para evitar que se repitan en cada página 

**Procesos y subprocesos - entry_indicators**  
- [x] Selección de periodos poner literal (abierto)  en los periodos 
- [x] STG pone métrica y debería ser Indicador 
- [x] tabla plantilla subprocess titulo sub process y no plantilla por 
- [x] mensaje guardar datos:  no muestra mensaje success notice 
- [x] anular enter

**Comment by palomahnhp** [comment]
- [ ] Opción Salir => cierre sesión y mensaje rojo y/o cerrar ventana tras un segundo  
- [ ] Cambio escudo a última versión => Calidad ya ha publicado el nuevo logo para Intranet 154X50
- [ ] PDF Resumen:  sacar los totales de tfoot para evitar que se repitan en cada página 
- [ ] Procesos y subprocesos | Selección de periodos poner literal (abierto)  en los periodos modificables

- [ ]

**Comment by palomahnhp** [comment]
Las primeras opción se pasan a issues independientes
